#define SL_VERSION_MAJOR 7
#define SL_VERSION_MINOR 8
#define SL_VERSION_MICRO 2
#define SL_VERSION 7.8.2

#define HAVE_ANSI_FOR_SCOPE 1
#define HAVE_NAMESPACE_STD 1

#define HAVE_SHORT 1
#define HAVE_SHORT_BITS 16
#define HAVE_INT 1
#define HAVE_INT_BITS 32
#define HAVE_LONG 1
#define HAVE_LONG_BITS 64
#define HAVE_LONG_LONG 1
#define HAVE_LONG_LONG_BITS 64
#define HAVE_SIZE_T 1
#define HAVE_SIZE_T_BITS 64

#define HAVE_LONG_DOUBLE 1

#define HAVE_LIBM 1
#define HAVE_LRINT 1
#define HAVE_LRINTF 1

#define HAVE_FUNCTION 1
/* #undef HAVE_FUNC */
#define HAVE_PRETTY_FUNCTION 1

#define HAVE_PRIVATE_SGI_RESTRICT 1
#define HAVE_PRIVATE_RESTRICT 1
/* #undef HAVE_RESTRICT */

#define HAVE_STL_UNORDERED_CONTAINERS 1
#define HAVE_STL_TR1_UNORDERED_CONTAINERS 1
/* #undef HAVE_STL_TR1_UNORDERED_CONTAINERS_MSVC */

#define HAVE_POSIX_THREADS 1
/* #undef HAVE_WIN32_THREADS */
